import "@/styles/index.scss";
import "bootstrap/dist/css/bootstrap.css";

import Header from "@/components/global/Header";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body>{children}</body>
    </html>
  );
}
